import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import test from 'node:test';
const assets=new URL('../app/src/main/assets/',import.meta.url);
const ctx={};vm.createContext(ctx);vm.runInContext(await fs.readFile(new URL('engine.js',assets),'utf8'),ctx);vm.runInContext((await fs.readFile(new URL('catalog.js',assets),'utf8')).replace('window.CATALOG','globalThis.CATALOG'),ctx);
const E=ctx.Energy,p={...E.defaults,age:35,height:170,weight:70,rhr:65};
function check(label,f){test(label,f);}const near=(a,b)=>assert.ok(Math.abs(a-b)<.01,`${a} != ${b}`);
check('Japanese male BMR matches Excel',()=>near(E.bmr(p),1538.1032011466793));
check('Female and age coefficients',()=>{near(E.bmr({...p,sex:'女性'}),1407.3554706163407);assert.ok(E.bmr({...p,age:65})<E.bmr(p));});
check('Special conditions and out of range disabled',()=>{assert.equal(E.bmr({...p,special:true}),null);assert.equal(E.bmr({...p,age:19}),null);});
check('Catalog count and source IDs',()=>{assert.equal(ctx.CATALOG.foods.length,90);assert.equal(ctx.CATALOG.activities.length,42);assert.equal(new Set(ctx.CATALOG.foods.map(x=>x.id)).size,90);});
const tea=ctx.CATALOG.foods.find(f=>f.name==='珍珠奶茶(去冰,全糖)'),cooking=ctx.CATALOG.activities.find(a=>a.name==='煮菜／備料 輕度');
check('Drink finished weight and oil sugar accounting',()=>{near(E.food({item:tea,amount:500,oil:0,sugar:0}).kcal,470);near(E.food({item:tea,amount:100,oil:5,sugar:10}).kcal,179);});
check('Custom portion unit and unknown protein',()=>{const f=E.food({item:{unit:'份',kcal:300,protein:null},amount:2,oil:0,sugar:0});near(f.kcal,600);assert.equal(f.protein,null);});
check('Routine activity excluded, extra net deducts baseline',()=>{near(E.activity({item:cooking,minutes:60,hr:null,extra:false},p).net,0);near(E.activity({item:cooking,minutes:60,hr:null,extra:true},p).net,140-E.bmr(p)*1.2/24);});
check('Heart rate is intensity only',()=>{const e={item:cooking,minutes:60,hr:125,extra:true};near(E.activity(e,p).net,E.activity({...e,hr:170},p).net);assert.equal(E.activity({...e,hr:240},p).intensity,'心率需核對');});
const d={profile:p,foods:[{item:tea,amount:500,oil:0,sugar:0}],activities:[],foodComplete:false,activityComplete:true};
check('Incomplete days do not yield deficits',()=>{assert.equal(E.day(d,p).deficit,null);assert.ok(E.day({...d,foodComplete:true},p).complete);});
check('Overlapping total duration over day blocked',()=>assert.equal(E.day({...d,activities:[{item:cooking,minutes:1441,hr:null,extra:true}]},p).tdee,null));
check('Underweight fat-loss target withheld',()=>assert.equal(E.day({...d,profile:{...p,weight:40},foodComplete:true},p).target,null));
const base={version:1,profile:p,foods:[tea],activities:[cooking],days:{}};
check('Reject malformed backups and missing profile parameters',()=>{assert.throws(()=>E.validateState({...base,profile:{sex:'男性'}}));assert.throws(()=>E.validateState({...base,foods:[{...tea,kcal:-1}]}));E.validateState(base);});
