import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
const assets=new URL('../app/src/main/assets/',import.meta.url);
const ctx={};vm.createContext(ctx);vm.runInContext(await fs.readFile(new URL('engine.js',assets),'utf8'),ctx);vm.runInContext((await fs.readFile(new URL('catalog.js',assets),'utf8')).replace('window.CATALOG','globalThis.CATALOG'),ctx);
const E=ctx.Energy,p={...E.defaults,age:35,height:170,weight:70,rhr:65};
const checks=[];function check(label,f){f();checks.push(label);}const near=(a,b)=>assert.ok(Math.abs(a-b)<.01,`${a} != ${b}`);
check('Japanese male BMR matches Excel',()=>near(E.bmr(p),1538.1032011466793));
check('Female and age coefficients',()=>{near(E.bmr({...p,sex:'女性'}),1407.3554706163407);assert.ok(E.bmr({...p,age:65})<E.bmr(p));});
check('Special conditions and out of range disabled',()=>{assert.equal(E.bmr({...p,special:true}),null);assert.equal(E.bmr({...p,age:19}),null);});
check('Catalog count and source IDs',()=>{assert.equal(ctx.CATALOG.foods.length,90);assert.equal(ctx.CATALOG.activities.length,42);assert.equal(new Set(ctx.CATALOG.foods.map(x=>x.id)).size,90);});
const tea=ctx.CATALOG.foods.find(f=>f.name==='珍珠奶茶(去冰,全糖)'),cooking=ctx.CATALOG.activities.find(a=>a.name==='煮菜／備料 輕度');
check('Drink finished weight and oil sugar accounting',()=>{near(E.food({item:tea,amount:500,oil:0,sugar:0}).kcal,470);near(E.food({item:tea,amount:100,oil:5,sugar:10}).kcal,179);});
check('Custom portion unit and unknown protein',()=>{const f=E.food({item:{unit:'份',kcal:300,protein:null},amount:2,oil:0,sugar:0});near(f.kcal,600);assert.equal(f.protein,null);});
check('Routine activity excluded, extra net deducts baseline',()=>{near(E.activity({item:cooking,minutes:60,hr:null,extra:false},p).net,0);near(E.activity({item:cooking,minutes:60,hr:null,extra:true},p).net,140-E.bmr(p)*1.2/24);});
check('Heart rate is intensity only',()=>{const e={item:cooking,minutes:60,hr:125,extra:true};near(E.activity(e,p).net,E.activity({...e,hr:170},p).net);assert.equal(E.activity({...e,hr:240},p).intensity,'心率需核對');});
const d={profile:p,foods:[{item:tea,amount:500,oil:0,sugar:0}],activities:[],foodComplete:false,activityComplete:true};
check('Incomplete days do not yield deficits',()=>{assert.equal(E.day(d,p).deficit,null);assert.ok(E.day({...d,foodComplete:true},p).complete);});
check('Overlapping total duration over day blocked',()=>assert.equal(E.day({...d,activities:[{item:cooking,minutes:1441,hr:null,extra:true}]},p).tdee,null));
check('Underweight fat-loss target withheld',()=>assert.equal(E.day({...d,profile:{...p,weight:40},foodComplete:true},p).target,null));
const base={version:1,profile:p,foods:[tea],activities:[cooking],days:{}};
check('Reject malformed backups and missing profile parameters',()=>{assert.throws(()=>E.validateState({...base,profile:{sex:'男性'}}));assert.throws(()=>E.validateState({...base,foods:[{...tea,kcal:-1}]}));E.validateState(base);});
await fs.mkdir(new URL('../test-results/',import.meta.url),{recursive:true});
const browser=await chromium.launch(process.env.ENERGY_TEST_BROWSER==='chromium'?{headless:true}:{channel:'chrome',headless:true});
try{
 const context=await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:1,acceptDownloads:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(new URL('index.html',assets).href);await page.getByRole('heading',{name:'今天的能量'}).waitFor();
 await page.getByRole('button',{name:'填寫設定'}).click();
 for(const [name,value]of Object.entries({age:'35',height:'170',weight:'70',rhr:'65'}))await page.locator(`#profile-form [name=${name}]`).fill(value);
 await page.getByRole('button',{name:'儲存並套用至此日與未來新日期'}).click();
 await page.locator('nav [data-page=today]').click();
 await page.locator('[data-action=food-add]').click();await page.locator('#item-picker').selectOption(tea.id);await page.locator('[name=amount]').fill('500');await page.locator('#edit-form button[type=submit]').click();
 await page.locator('#foodComplete').check();await page.locator('#activityComplete').check();
 check('UI food save and daily deficit',()=>assert.ok(true));
 await page.locator('nav [data-page=catalog]').click();await page.locator('[data-action=catalog-add]').click();
 await page.locator('#edit-form [name=name]').fill('自訂整杯鮮奶茶');await page.locator('#edit-form [name=unit]').selectOption('份');await page.locator('#edit-form [name=kcal]').fill('300');await page.locator('#edit-form [name=protein]').fill('5');await page.locator('#edit-form button[type=submit]').click();
 const customId=await page.evaluate(()=>state.foods.find(i=>i.name==='自訂整杯鮮奶茶').id);
 await page.locator('nav [data-page=today]').click();await page.locator('[data-action=food-add]').click();await page.locator('#item-picker').selectOption(customId);await page.locator('[name=amount]').fill('1');await page.locator('#edit-form button[type=submit]').click();
 assert.equal(await page.evaluate(()=>Energy.food(day().foods[1]).kcal),300);assert.equal(await page.evaluate(()=>day().foodComplete),false);checks.push('Custom whole-cup unit and completion reset');
 await page.locator('nav [data-page=catalog]').click();await page.locator(`[data-action=catalog-edit][data-id="${customId}"]`).click();await page.locator('[name=kcal]').fill('450');await page.locator('#edit-form button[type=submit]').click();
 assert.equal(await page.evaluate(()=>Energy.food(day().foods[1]).kcal),300);checks.push('Catalog edits preserve saved nutrition snapshots');
 await page.locator('nav [data-page=today]').click();await page.locator('[data-action=food-edit][data-index="1"]').click();await page.locator('#edit-form button[type=submit]').click();assert.equal(await page.evaluate(()=>Energy.food(day().foods[1]).kcal),300);checks.push('Record edits use original nutrition snapshot');
 await page.locator('[data-action=activity-add]').click();await page.locator('#item-picker').selectOption(cooking.id);assert.equal(await page.locator('[name=extra]').isChecked(),false);await page.locator('#edit-form button[type=submit]').click();
 assert.equal(await page.evaluate(()=>Energy.activity(day().activities[0],day().profile).net),0);checks.push('Routine cooking defaults excluded from extra energy');
 await page.locator('#foodComplete').check();await page.locator('#activityComplete').check();const firstDate=await page.locator('#date').inputValue(); const prior=new Date(firstDate+'T12:00:00');prior.setDate(prior.getDate()-1);const previousDate=prior.getFullYear()+'-'+String(prior.getMonth()+1).padStart(2,'0')+'-'+String(prior.getDate()).padStart(2,'0');
 await page.screenshot({path:fileURLToPath(new URL('../test-results/app-today.png',import.meta.url)),fullPage:true});
 await page.reload();assert.equal(await page.evaluate(()=>day().foods.length),2);assert.ok(await page.evaluate(()=>Energy.day(day(),state.profile).complete));checks.push('Persistence survives page reload');
 await page.locator('#date').fill(previousDate);await page.locator('#date').dispatchEvent('change');await page.locator('[data-action=food-add]').click();await page.locator('#item-picker').selectOption(customId);await page.locator('[name=amount]').fill('1');await page.locator('#edit-form button[type=submit]').click();await page.locator('#foodComplete').check();await page.locator('#activityComplete').check();
 await page.locator('nav [data-page=settings]').click();await page.locator('[name=sex]').selectOption('女性');await page.locator('#profile-form button[type=submit]').click();assert.equal(await page.evaluate(d=>state.days[d].profile.sex,firstDate),'男性');checks.push('Past and current profiles remain independent');
 await page.locator('nav [data-page=history]').click();await page.locator('[data-period=all]').click();assert.equal(await page.evaluate(()=>historyRows().filter(r=>r.result.complete).length),2);checks.push('Two valid days accumulated');
 const dl=page.waitForEvent('download');await page.locator('[data-action=csv-export]').click();const csv=await fs.readFile(await(await dl).path(),'utf8');assert.ok(csv.includes('日期')&&csv.includes(previousDate));checks.push('CSV download with daily totals');
 await page.locator('nav [data-page=settings]').click();const backupDl=page.waitForEvent('download');await page.locator('[data-action=backup-export]').click();const backup=await fs.readFile(await(await backupDl).path(),'utf8');E.validateState(JSON.parse(backup));await page.evaluate(t=>window.onBackupLoaded(t),backup);assert.equal(await page.evaluate(()=>Object.keys(state.days).length),2);checks.push('JSON backup export and confirmed import');
 await page.locator('nav [data-page=catalog]').click();await page.locator('[data-type=activities]').click();await page.locator('[data-action=catalog-add]').click();await page.locator('#edit-form [name=name]').fill('自訂活動測試');await page.locator('[name=rate]').fill('4.5');await page.locator('#edit-form button[type=submit]').click();assert.ok(await page.evaluate(()=>state.activities.some(a=>a.name==='自訂活動測試'&&a.rate===4.5)));checks.push('Custom activity creation');
 await page.locator('nav [data-page=catalog]').click();await page.locator('[data-type=foods]').click();await page.locator(`[data-action=catalog-edit][data-id="${customId}"]`).click();await page.locator('[data-action=catalog-hide]').click();assert.equal(await page.evaluate(id=>state.foods.find(x=>x.id===id).hidden,customId),true);assert.equal(await page.evaluate(d=>state.days[d].foods[1].item.kcal,firstDate),300);await page.locator('[data-action=restore-hidden]').click();assert.equal(await page.evaluate(id=>state.foods.find(x=>x.id===id).hidden,customId),false);checks.push('Hide and restore items preserve history');
 await page.locator('nav [data-page=settings]').click();await page.locator('[name=age]').fill('35.5');await page.locator('#profile-form button[type=submit]').click();assert.ok((await page.locator('#profile-error').textContent()).includes('整數'));await page.locator('[name=age]').fill('35');checks.push('Fractional ages rejected before saving');
 await page.evaluate(()=>window.Native={save:()=>false});await page.locator('#profile-form button[type=submit]').click();assert.ok((await page.locator('#toast').textContent()).includes('尚未保存'));assert.ok((await page.locator('#app').textContent()).includes('資料讀取或儲存失敗'));checks.push('Native save failures shown without claiming success');
 assert.deepEqual(errors,[]);checks.push('No runtime browser errors');
 await fs.writeFile(new URL('../test-results/app-test-report.json',import.meta.url),JSON.stringify(checks,null,2));console.log(JSON.stringify({passed:checks.length,checks}));
}finally{await browser.close();}
